name: 'ecommerce-database-end-to-end'
version: '1.0.0'
config-version: 2

profile: 'ecommerce-database-end-to-end'

model-paths: ["ecommerce-database-end-to-end/models"]
target-path: "target"
clean-targets: ["target"]

models:
  ecommerce-database-end-to-end:
    staging:
      materialized: view
    dim:
      materialized: table
    fato:
      materialized: table
