x-common-settings: &common-settings
  restart: "no"
  cpus: 1
  mem_limit: 1g
  memswap_limit: 1g
  logging:
    driver: "json-file"
    options:
      max-size: "10m"
      max-file: "1"

services:
  # Postgresql
  maquina1:
    <<: *common-settings
    depends_on:
      maquina2:
        condition: service_started
    build:
      context: ./maquina1
    container_name: maquina1
    hostname: maquina1
    ports:
      - "15432:5432"
      - "2221:22"
    volumes:
      - ./maquina1/data:/var/lib/postgresql/data:rw
      - ./maquina1/log:/var/lib/postgresql/log:rw
      - maquina1-ssh:/var/lib/postgresql/.ssh:rw
    networks:
      rede:
        ipv4_address: 110.0.0.111
    extra_hosts:
      maquina2: 110.0.0.112
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
    command: |
      -c "archive_mode=on"
      -c archive_command='pgbackrest --stanza=maquina1 archive-push "%p"'
      -c "max_wal_senders=3"
      -c "wal_level=replica"
      -c "wal_keep_size=64MB"

  # Backup Server
  maquina2:
    <<: *common-settings
    build:
      context: ./maquina2
    container_name: maquina2
    hostname: maquina2
    ports:
      - "2222:22"
    volumes:
      - ./maquina2/data:/var/lib/pgbackrest:rw
      - ./maquina2/log:/var/log/pgbackrest:rw
      - maquina2-ssh:/var/lib/postgresql/.ssh:rw
    networks:
      rede:
        ipv4_address: 110.0.0.112
    extra_hosts:
      maquina1: 110.0.0.111

  maquina3:
    <<: *common-settings
    depends_on:
      postgresql-exporter:
        condition: service_started
    image: prom/prometheus
    container_name: prometheus
    hostname: prometheus
    volumes:
        - ./maquina3/prometheus.yml:/etc/prometheus/prometheus.yml
        - prometheus-data:/prometheus
    command:
        - '--config.file=/etc/prometheus/prometheus.yml'
        - '--storage.tsdb.path=/prometheus'
        - '--web.console.libraries=/usr/share/prometheus/console_libraries'
        - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
        - "9090:9090"
    networks:
      rede:
        ipv4_address: 110.0.0.113

  postgresql-exporter:
    <<: *common-settings
    depends_on:
      maquina1:
        condition: service_healthy
    image: prometheuscommunity/postgres-exporter
    container_name: postgresql-exporter
    hostname: postgresql-exporter
    ports:
      - "9187:9187"
    environment:
      DATA_SOURCE_NAME: "postgresql://postgres:postgres@maquina1:5432/postgres?sslmode=disable"
    networks:
      rede:
        ipv4_address: 110.0.0.114

  grafana:
    <<: *common-settings
    depends_on:
      maquina3:
        condition: service_started
    image: grafana/grafana
    container_name: grafana
    hostname: grafana
    environment:
        GF_SECURITY_ADMIN_PASSWORD: senha
        GF_USERS_ALLOW_SIGN_UP: false
    ports:
        - "3000:3000"
    networks:
      rede:
        ipv4_address: 110.0.0.115

networks:
  rede:
    name: rede
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 110.0.0.0/24

volumes:
  maquina1-ssh:
    name: maquina1-ssh
    driver: local
  maquina2-ssh:
    name: maquina2-ssh
    driver: local
  prometheus-data:
    name: prometheus-data
    driver: local
